# Generated by Django 4.0.6 on 2022-08-04 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_question_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('payment_id', models.CharField(default=uuid.uuid1, editable=False, max_length=36, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(36)], verbose_name='id')),
                ('summ', models.IntegerField(null=True, verbose_name='Amount')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Payment confirmed')),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='telegram_bot.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='telegram_bot.person', verbose_name='Guest')),
            ],
        ),
    ]
