# Generated by Django 4.0.6 on 2022-08-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Processed'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, verbose_name='Question'),
        ),
    ]
