# Generated by Django 4.0.6 on 2022-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_alter_question_processed_alter_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=3000, verbose_name='Message')),
                ('users', models.ManyToManyField(blank=True, related_name='got_admin_messages', to='telegram_bot.person', verbose_name='Users (if blank, will send to everyone in database)')),
            ],
        ),
    ]
