# Generated by Django 4.0.6 on 2022-08-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='was_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
    ]
