# Generated by Django 4.0.6 on 2022-08-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_alter_donate_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='paid_at',
            field=models.DateTimeField(blank=True, verbose_name='Paid at'),
        ),
    ]
