# Generated by Django 4.0.6 on 2022-08-08 11:53

from random import choices, randint
from django.db import migrations


def add_test_questions(apps, schema_editor):
    Lecture = apps.get_model('telegram_bot', 'Lecture')
    Question = apps.get_model('telegram_bot', 'Question')
    lectures = Lecture.objects.all()
    for lecture in lectures:
        speaker = lecture.speaker
        event = lecture.event
        participants = event.participants.all()
        for _ in range(randint(0, 5)):
            Question.objects.get_or_create(
                event=event,
                guest=choices(participants)[0],
                speaker=speaker,
                question=f'{_} testing question for {speaker} on {event}'
            )



class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_alter_donate_paid_at'),
    ]

    operations = [
        migrations.RunPython(add_test_questions)
    ]
